### ISSUE TITLE
jde-help-class: (void-function sort-helper)

### ISSUE THREAD

**Issue by flesner** [jdee-emacs/jdee#10]
it appears that checkin a3f95b051e430c27f00dc17e3c995cbdf71807bb broke the javadoc helper classes. my current stack trace:

Debugger entered--Lisp error: (void-function sort-helper)
  sort-helper("org.apache.commons.httpclient.HttpClient" "twitter4j.internal.http.HttpClient")
  sort(("sun.net.www.http.HttpClient") sort-helper)
  jde-choose-class(("sun.net.www.http.HttpClient") "Select qualified class" #("HttpClient" 0 9 (fontified t face font-lock-type-face) 9 10 (fontified t c-type c-decl-id-start face font-lock-type-face)) nil)
  jde-read-class()
  (list (jde-read-class))
  call-interactively(jde-help-class record nil)
  command-execute(jde-help-class record)
  execute-extended-command(nil "jde-help-class")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

i'm using emacs 24.5.1

**Comment by daveloyall** [comment]
Maybe `cl-flet` isn't being used correctly?  ...I'm not very good at elisp. :)

**Comment by flesner** [comment]
fixed, thanks stephen.
