### ISSUE TITLE
Incomplete `dir` file prevents manual showing up in Emacs Directory node (installing over melpa)

### ISSUE THREAD

**Issue by rudi** [jdee-emacs/jdee#108]
The `dir` file of JDEE 20170217.22 (installed via melpa) does not add `jdee.info` to the Emacs Info directory node.  Adding something like the following lines to the end of `dir` makes the JDEE manual appear in the directory.  (Adding it to the `Emacs` section since all other packages installed via melpa do the same.)

I'd have submitted a patch but could not see how/where the `dir` file is generated.

```
Emacs
* JDEE: (jdee).         A sophisticated Java IDE for Emacs.
```

**Comment by pwojnowski** [comment]
AFAIK the "dir" file is generated by cask, when the package is created. But there must be some way to generate (or include) it correctly so that the above entry is included.
