### ISSUE TITLE
looking for "dash"?

### ISSUE THREAD

**Issue by cvarner** [jdee-emacs/jdee#109]
Running under emacs 25.1, I get (with --debug-init-file):

Debugger entered--Lisp error: (file-error "Cannot open load file" "No such file or directory" "dash")
  require(dash)
  eval-buffer(#<buffer  *load*-818619> nil "/home/cv7462/.emacs.d/jdee/jdee-maven.el" nil t)  ; Reading at buffer position 945
  load-with-code-conversion("/home/cv7462/.emacs.d/jdee/jdee-maven.el" "/home/cv7462/.emacs.d/jdee/jdee-maven.el" nil t)
  require(jdee-maven)

Where do I find "dash"? Didn't see it in melpa.

**Comment by pwojnowski** [comment]
Strange. It's definitely there: https://melpa.org/#/dash

**Comment by libnoon** [comment]
Dash is in melpa.  I guess we can close this ticket.

**Comment by pwojnowski** [comment]
Just one thing, @cvarner how did you install JDEE? I don't think it was from MELPA (as it supposed to be done), because I don't see ".emacs.d/elpa/jdee" in your logs. When you install through MELPA, then dash will be installed automatically as a dependency.
