### ISSUE TITLE
makeinfo instructions in ./README.md are incorrect

### ISSUE THREAD

**Issue by jbapple-cloudera** [jdee-emacs/jdee#118]
README.md says:

> There is a texinfo documentation: doc/jdee.texi.
> 
> To generate Info, HTML and PDF documentation:
> 
> - Install texinfo.
> 
> - For PDF generation, you also need texi2dvi, texinfo-tex, texlive-ec
>   and texlive-cm-super.
> 
> - In the doc/ subdirectory, run: ```makeinfo --info --html --pdf```

That instruction fails for me:

```
jdee/doc$ makeinfo --info --html --pdf
makeinfo: missing file argument.
Try `makeinfo --help' for more information.
jdee/doc$ makeinfo --version
makeinfo (GNU texinfo) 5.2
```

**Comment by pwojnowski** [comment]
I've corrected the documentation. It suppose to be ```makeinfo --info --html --pdf jdee.texi```.
BTW JDEE from MELPA ships with INFO docs out of the box, so you don't have to do anything if you are fine with info.
