### ISSUE TITLE
eieio-oref problem on startup

### ISSUE THREAD

**Issue by RadicalZephyr** [jdee-emacs/jdee#123]
Using emacs 25.2.1, and jdee 2.4.1 binary installation on startup I get an error:

`eieio-oref called on a class: jde-plugin`

In looking into the code, it looks like the change needed is to change the `oref` function to `oref-default` when trying to access the `plugins` class field on the `jde-plugin` class.

**Comment by pwojnowski** [comment]
It is fixed in newer JDEE. Please install it from MELPA.
