### ISSUE TITLE
Idle Parse Error in Emacs 26.0.50 (20170521)

### ISSUE THREAD

**Issue by yangwen0228** [jdee-emacs/jdee#124]
The jdee works fine in Emacs early version 26.0.50.4 (20170117), however, after I update it to the latest versoin. It always has this error:
`Idle Parse Error: "#<buffer Demo1.java> - Invalid slot type: jdee-parse-method-map, tree, sequence, #s(avl-tree- [nil nil nil 0] jdee-parse-method-map-compare-fcn)"`

I suspect this error is caused by the package eieio, but I don't know too much about eieio, so I don't know how to fix this. Does anyone else suffer this same problem? Or any solutions?

Thanks in advance!

**Comment by pwojnowski** [comment]
My guess is that JDEE was compiled with the older version of Emacs and now you try to run it in the newer one. Please try to recompile or reinstall JDEE in the newer version to have files compiled.

**Comment by yangwen0228** [comment]
@pwojnowski Yes, you are right! I delete all the packages and reinstall them from melpa, and delete all the configuration elc files, and recompile the configuration files. Then the error disappears. Thank you very much!
