### ISSUE TITLE
Bad delimiter for ant.home

### ISSUE THREAD

**Issue by vincentb1** [jdee-emacs/jdee#132]
Hello,
In jdee-ant.el, we have the following code:
``` Elisp
	   (if ant-home
	       (concat
		" -Dant.home="
		(if (or
		     (string-match " " ant-home) ;; Quote path if it
		     (string-match "." ant-home));; contains a space
		    (concat delimiter ant-home delimiter)  ;; or period.
		  ant-home)))
```
I have the following comments:

- First of all the `(string-match "." ant-home)` always matches, because the regexp "." matches any non-eol characters, so the comment &laquo;&nbsp;Quote path if is contains a space&nbsp;&raquo; is erroneous, or better said, the code is erroneous.
- Second, `string-match-p` is better than `string-match` here, as it does not affect the match data
- Third, `delimiter` can be `'` under MSWindows, and this breaks this. This is what happened to me, and that is why I am reporting the problem.

**Comment by pwojnowski** [comment]
I've changed the delimiter to be always " (double quote). IIUC it is used to quote path to the Ant Home. In Linux double quote (") and single quote (') work, but in Windows only double quotes (") can be used. The problem was that **delimiter** variable is based on ```jdee-ant-invocation-method```.

Also to me the "." regexp seems to be wrong, so I removed it.

Please, verify if it works as I don't have access to Windows. Thanks!

**Comment by vincentb1** [comment]
It did not work for me at once just by reloading the file, because there is some `(require 's)`  at line 95. So, I installed the `s` package (which is marked as obsolete by `package-list-packages`). And I reloaded `jdee-ant.el`, and it did not work again, because I had to reload my `prj.el` before.
Once `prj.el` reloaded, it worked as expected.
The reason why I needed to reload `prj.el` is that it contains the following:
```Elisp
(jdee-project-file-version "1.0")
(jdee-set-variables
; [...]
 '(jdee-ant-buildfile "c:/Nos_Programmes/MinGW/local/projects/jpicedt_dev/jpicedt/build.xml")
 '(jdee-build-function (quote jdee-ant-build))
; [...]
```
If I do not give the full path of build file, it does not work, although the `prj.el` and `build.xml` are in the same dir.

**Comment by vincentb1** [comment]
Just as a suggestion, IMHO it would be better to have a module `jdee-compatibility.el` in which you would have the following:
```Elisp
(unless (functionp 'string-match-p)
  (defsubst string-match-p (regexp string &optional start)
    (save-match-data (string-match regexp string start))))
(provide 'jdee-compatibility)
```
And then in `jdee-ant.el`, you would replace `(require 's)` and `(s-match `&hellip;`)` by resp. `(require 'jdee-compatibility)` and `(string-match-p `&hellip;`)`

**Comment by pwojnowski** [comment]
[s.el](https://github.com/magnars/s.el) is a string manipulation library and is available in Melpa. Maybe it was marked as obsoleted, because there was a newer version? This way or another, it should be installed automatically when JDEE is installed from MELPA.

I'm not sure why you had to set full path to the build file. But that seems to be another issue.

**Comment by vincentb1** [comment]
Concerning why I needed the full path for `jdee-ant-buildfile`, the reason was that `jdee-ant-enable-find` is `nil` by default. Now I have customized it to `t`, and having `jdee-ant-buildfile` set just to `build.xml` is OK.

Concerning `s.el`, I am not really opinionated on this. Frankly speaking I did not know `s`, and looking at [s on melpa](https://melpa.org/#/s) there is no mention of obsolescence. My suggestion was just related to this that given such a tiny piece of code, loading a full package might be overkill. Also, looking at the code of `s-match`, it does quite more than just saving the match data, there is some listing of all the matches, and this processing is not used by jdee-ant.

**Comment by pwojnowski** [comment]
Good that ```jdee-and-buildfile``` works.

Regarding s.el - I wanted to add this library to the project to have simple and intuitive string processing and this was the first occasion. ```s-matches?``` (not s-match) is just a thin wrapper around ```string-match-p```.

Anyway, please close the issue if you consider the delimiter handling correct.

**Comment by vincentb1** [comment]
Thank you for your support !
