### ISSUE TITLE
Can't run customize for jdee-server-dir

### ISSUE THREAD

**Issue by FreddieV4** [jdee-emacs/jdee#135]
## My Emacs version:
GNU Emacs 25.3.1
## My JDEE version:
JDE 2.4.2
## Stacktrace (if applicable):
![image](https://user-images.githubusercontent.com/8339018/31111956-f428484e-a7de-11e7-961d-f80f95bde8ef.png)

## Other info you consider could help to fix it:
I followed the installation information found in this README; through MELPA. Then went to https://github.com/jdee-emacs/jdee-server and got all the way up to step 9 with no problems, but failed at step 9.

```
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T15:39:06-04:00)
Maven home: /opt/apache-maven-3.5.0
Java version: 1.8.0_111, vendor: Oracle Corporation
```

If there's any other helpful information you think I might be able to provide you with, please let me know 🙂

**Comment by pwojnowski** [comment]
Can you see ```jdee-server-dir``` when you try: ```M-x customize-group RET jdee RET``` ?

**Comment by FreddieV4** [comment]
Yes. That worked!. Thanks so much 😄

**Comment by drrost** [comment]
No, in my case it doesn't :(

**Comment by timaiken** [comment]
Nor in mine. Any assistance would be most appreciated. Thanks.

**Comment by rosso-** [comment]
I can't find jdee in MELPA.
