### ISSUE TITLE
Java 10 Support

### ISSUE THREAD

**Issue by vrdhn** [jdee-emacs/jdee#145]
Half the software developers have a way of keeping the other half surprised and busy !
It'll be good to be able to handle java 10.  

```
$ ./jdk1.8.0_172/bin/javac -version
javac 1.8.0_172

$ ./jdk-10.0.1/bin/javac -version
javac 10.0.1

```

Thanks for this package, I'm just starting to use it as I've a java project now.

**Comment by andreas-marschke** [comment]
@vrdhn Thanks for opening this issue. Can you elaborate as to what exactly is missing in your case or failing to be detected? From the issue you've opened I'm not entirely clear what the issue is you're trying to solve or proposal you are suggesting.

**Comment by udalrich** [comment]
I pushed a change earlier today that let JDEE identify Java 10.  Java 10 support should be identical to Java 9 support.
