### ISSUE TITLE
Setup travis-ci builds

### ISSUE THREAD

**Issue by pwojnowski** [jdee-emacs/jdee#2]
There should be builds for Emacsen from 24.3 to Emacs-master.

**Comment by bbatsov** [comment]
You can use `cider`'s Travis setup for inspiration https://github.com/clojure-emacs/cider/blob/master/.travis.yml

**Comment by phillord** [comment]
Probably need to shift to using evm. Damien's ppa is old history now (unfortunately!). In the short term targetting only Emacs current makes sense, but once 25 comes out, it is probably worth tracking 24.4 as long as possible.

**Comment by pwojnowski** [comment]
@bbatsov Travis config works great. Thanks!
@plandes Any news about Travis build?

**Comment by plandes** [comment]
Hi,  I asked that we take this off line.  Please respond to the email I sent or directly email me.
