### ISSUE TITLE
collab with ensime

### ISSUE THREAD

**Issue by fommil** [jdee-emacs/jdee#20]
hi, welcome to github.

We're keen to add straight Java support into ensime:

https://github.com/ensime/ensime-server/

it would be good if we could work together to avoid fragmentation of Java support. Is there anything that immediately jumps out that we could share?

I'm very keen that we use the official java compile tree API in the background, and stay clear of Eclipse.

**Comment by phillord** [comment]
I think that things are in a bit of flux at the moment, and working out
how to make Emacs an generalised JVM hosted language editor is
non-trivial, although part of my interest also stems from the same kind
of idea -- although I tend to use clojure rather than scala.

One obvious issue at the moment is that we have so many protocols for
interacting with the JVM. JDEE (as stands) is using beanshell (which is
using a "protocol" based around either strings or eval'able Emacs-Lisp).
Clojure is using nrepl. Malabar-mode is using a Groovy console. And
ensime is using, is it swank? And all of them are using external
processes also (i.e. for launching maven, lein or sbt).

I've been working on repurposing the clojure environment to provide an
environment for Java editing, and have a nrepl connection working for
that purpose -- so far I have class browsing and stacktrace handling.
How much time I will have for this is very open question.

Not sure where we go from here, to be honest, but now is the time to
have these discussions. At least splitting JDEE up so that there is the
Java mode, and then JVM connection as a minor mode should make JDEE
resuable for you.

Phil

**Comment by fommil** [comment]
@phillord cool! Actually we now also have a JSON based protocol of messages in and out because we are cross editor (we call that JERK for the TCP variant and JERKY for the WebSockets one). We're moving to S-Expressions over WebSockets (SWANKY), which should reduce our emacs lisp footprint.

Adding Java support to ENSIME is actually reasonably easy --- all we really need is to hook up the Java compiler tree API to be able to get type at point. Additional features such as passive suggestions are a bigger job, but we have a framework in mind (talking to scala compiler contributors we're moving towards a nice scala solution, in java world we were hoping to just depend/copy the relevant netbeans code to be honest).

We already index the entire classpath and support documentation hosting / debugging. We have no client side support for Java, this is probably where we could benefit the most from collaborating with JDEE.

My understanding is that cider is so good that there is nothing ENSIME could add to the experience, other than supporting non-clojure files.

One thing I'd love to move us towards is a better protocol for suggested edits. i.e. diff files for all server suggestions and then come up with a client side (language agnostic) UI for previewing the suggestions --- just showing the raw diff can be really ugly and inappropriate for small suggestions but the diff might be perfect for cross file refactorings.

Other things emacs-side that would help a lot is to scrap some custom rendering code and rely more heavily on existing libraries. In addition to our own refactoring preview screen, we also have our own search result rendering and type inspector rendering... these all feel like MELPA should have something we can now use (when originally written none of this stuff existed).

These client side things are most certainly areas where we could benefit from working together.

**Comment by phillord** [comment]
Sam Halliday <notifications@github.com> writes:

> @phillord cool! Actually we now also have a JSON based protocol of messages in
> and out because we are cross editor (we call that JERK for the TCP variant and
> JERKY for the WebSockets one). We're moving to S-Expressions over WebSockets
> (SWANKY), which should reduce our emacs lisp footprint.

Yeah. nrepl is similar for similar reasons (the middleware for CIDER is
also being used by vim I think). There is some hope that nrepl could be
cross-language also (i.e. support R), but the current client for Emacs
is embedded in cider, for which @bbatsov has very good reasons.


> We already index the entire classpath and support documentation hosting /
> debugging. We have no client side support for Java, this is probably where we
> could benefit the most from collaborating with JDEE.

It sounds that way.

> My understanding is that cider is so good that there is nothing ENSIME could
> add to the experience, other than supporting non-clojure files.

CIDER is very rich now. I'm sure that the feature set of the two is
exactly overlapping in either way though.


> One thing I'd love to move us towards is a better protocol for
> suggested edits. i.e. diff files for all server suggestions and then
> come up with a client side (language agnostic) UI for previewing the
> suggestions --- just showing the raw diff can be really ugly and
> inappropriate for small suggestions but the diff might be perfect for
> cross file refactorings.

Or some sort of inner protocol anyway, inside the nrepl or your swanky.

The other thing that would be nice is a "connection selection and
editing tool". I can imagine a project with Java and Scala, or Scala and
Clojure or what ever with multiple JVM backends open at the same time.
Or an R nrepl server.

> Other things emacs-side that would help a lot is to scrap some custom
> rendering code and rely more heavily on existing libraries. In addition to our
> own refactoring preview screen, we also have our own search result rendering
> and type inspector rendering... these all feel like MELPA should have
> something we can now use (when originally written none of this stuff existed).
>
> These client side things are most certainly areas where we could
> benefit from working together.

Emacs needs far more gui widgets. Consider the magit front end and the
org-mode export front end. Both of them involve selecting a "main"
command, with options. Similar tasks, all custom code.

As before, all of these things seem good, but for JDEE at the moment
things are in flux, as we do not have anyone working on it at the level
of @bbatsov or yourself.

**Comment by pwojnowski** [comment]
Hi.
@fommil what do you mean by "java support" in ensime?

My understanding is that there is JVM that runs bytecode that can be generated from many languages (Java, Scala, Clojure, Groovy, etc.). Moreover the languages may coexist in the same project (for example main code in Java, tests in Groovy - very common config) so user could have uniform support for all of them (if possible) from Emacs - different modes for sources in different languages, but one metadata for the same project (e.g. Spring Application Context, JPA mappings, WS, etc.). Also support for different project management is cross-language - Maven, Gradle, Leiningen, etc.

So, in my mind there could be Emacs modes per language, one cross-language to JVM communication protocol, language support on JVM side, cross-language project support. So something like the Bridge pattern.

If that would be the case, then such a project would need a joint effort. IMHO the first thing to do would be the communication protocol. Projects could be refactored separately to use it. Then JVM side support could be joined.

What do you think about it? :-)

**Comment by fommil** [comment]
Yeah, I mean firstly adding Java language (ie compile tree) support to the ENSIME server component. We already have two protocols: one using sexpressions and another using JSON, which works really well for non-emacs clients. We'd be looking to extent that, and we have a framework that allows us to very easily do so. On the Emacs side, yeah there is loads of stuff we could be working on together.

**Comment by fommil** [comment]
But let's do something practical. Give us a couple of months to have something working for Java lang, and then we can chat about how to consolidate our efforts :-)

**Comment by phillord** [comment]
You are talking about adding more knowledge of Java source code, accessible via ENSIME?

That's very interesting, as it would be useful in JDEE also. My major concern at the moment is that we have two protocols for interacting between the JVM and Emacs (three if you include parsing process buffers!) in the shape of ENSIME and nrepl. I suspect we are already close to being too far down the line to fix this, if not over it.

It would be a shame if, for example, a mixed clojure/scala/java project required three (or more) JVMs for full functionality from Emacs (or vim!). Two many of the editing tool libraries are bundled with IDEs anyway. I can see why that has happened with netbeans/ecllipse and so forth, but it would be good if we can avoid it. I can see no reason why we should not have a scala library analyse Java source code then pass it through nrepl for clojure/java projects. Or have a clojure auto-complete library for Java be useful to ENSIME.

**Comment by fommil** [comment]
Yeah, I'm not sure what value we can add to clojure to be honest. They seem to have everything they need. Maybe better support for search or Java interoperability?

It's unlikely that we'll move away from the proposed websockets protocol because so many other editors are using it but if we could migrate the jdee server side components into a Java ENSIME layer, we could drop a protocol by sharing between Java and Scala. Groovy maybe also.

**Comment by fommil** [comment]
Anyway, I'm rambling. We (ENSIME) need to have some code that we can talk around. We have rolling releases, so we're happy to break protocols if the fix is "update your melpa" .

**Comment by arichiardi** [comment]
I wanted just to ask here whether the effort of a unified mode has had some progress and if not, where it is stuck and how to help.
Cannot believe I have to use IntelliJ for my Java work...

**Comment by plandes** [comment]
I assume you mean [lsp-mode](https://github.com/emacs-lsp/lsp-mode), which looks very nice.  Right off the bat the completion with `company-mode` is a motivation for me to move to it.  It seems to have momentum as well.  It would be great if it succeeds because remembering five keybindings across five languages is hard.

All right, let's let ENIME/JDEE integration die.  Maybe the path ahead is `lsp-mode`.

**Comment by phillord** [comment]
Also eglot which is in ELPA. It seems the way to go. I have never looked at LSP though -- it's enough to get data about code, but not sure if it will do the "compile" and "build" functionality that JDEE has.
