### ISSUE TITLE
JDEE Lisp nesting exceeds `max-lisp-eval-depth'

### ISSUE THREAD

**Issue by noxdafox** [jdee-emacs/jdee#24]
Whenever I launch jdee-mode I get the UI locked and I see a lot of messages lines like these:

    Lisp nesting exceeds `max-lisp-eval-depth' [2 times]
    Error during redisplay: (jit-lock-function 1) signaled (error "Lisp nesting exceeds `max-lisp-eval-depth'")

And a message line:

    Invalid slot type: jdee-db-cmd-set, debugger, jdee-db-debugger, [object jdee-db-jdb-1-6 "jdb 1.6" "Java debugger" "Java Debugger" unbound unbound nil unbound nil unbound nil unbound unbound "jdb" "jdb" unbound]

This happens with any buffer, even empty ones.

**Comment by noxdafox** [comment]
My bad, I added in my init file:

    (add-hook 'java-mode-hook 'jdee-mode)

And it was getting in a loop. I guess jdee-mode is started automagically in some other way.

**Comment by phillord** [comment]
Yeah, that will break it -- `jdee` is derived from `java-mode`, so calling `jdee-mode` forces `java` mode which will call the `java-mode-hook` and so forth.

If installed from MELPA, jdee *should* work automatically on any `*java` file. Is this not happening for you?

**Comment by noxdafox** [comment]
It works beautifully! I just didn't expect to get it "out of the box" in such a way, therefore I used the usual `add-hook` trick and ended up shooting in my own leg.

**Comment by phillord** [comment]
Glad it's working!
