### ISSUE TITLE
MELPA support ????

### ISSUE THREAD

**Issue by liar666** [jdee-emacs/jdee#27]
When clicking on the MELPA button on the project's github page: README.md I get:
"The repository at jdee-emacs/jdee was not found."

Also, there's nothing nammed "jd*" on the MELPA repository

**Comment by pwojnowski** [comment]
Hm... what is exact address that you are looking at? JDEE clearly is at MELPA: http://melpa.org/#/jdee

**Comment by liar666** [comment]
In fact I clicled on the link on the right of the MELPA button, which redirects to: 
https://travis-ci.org/jdee-emacs/jdee

Also I still can't see jdee in Emacs' package list. Could it be because I'm using the stable repository?

**Comment by pwojnowski** [comment]
Yes. Currently JDEE is only in MELPA unstable.
