### ISSUE TITLE
jdee-server required but not in MELPA :{

### ISSUE THREAD

**Issue by liar666** [jdee-emacs/jdee#28]
Hi,

I just attempted to do a jde-help-symbol through the C-c C-v C-w key binding and got the error:
Point `jdee-server-dir' to dir with JDEE jars.

According to:
https://stackoverflow.com/questions/32201761/point-jdee-server-dir-to-dir-with-jdee-jars-issue
I need to install jdee-server, but it is not in MELPA :{

**Comment by pwojnowski** [comment]
In "Requirements" section on JDEE page there is a link to JDEE Server, which you have to install manually - http://github.com/jdee-emacs/jdee-server.

Unfortunately we don't have better solution, yet. This separation allowed us to release elisp part to MELPA with one-time installation of Java part. Sorry. :-|
