### ISSUE TITLE
Automated Build

### ISSUE THREAD

**Issue by phillord** [jdee-emacs/jdee#3]
Would be good to add an automated build and dependency mechanism such as Cask.

This would facilitate the use of travis-ci, as well as the production of a pre-defined package which could be put onto marmalade.

**Comment by pwojnowski** [comment]
I tried to do that, but couldn't compile elisp files.
Probably because of: https://github.com/cask/cask/issues/275

**Comment by phillord** [comment]
Want to put your attempts up somewhere on a branch, and we can whether we can work on it together?

**Comment by pwojnowski** [comment]
But what to do with Java code? Is it possible to upload a JAR to (m)ELPA?

**Comment by plandes** [comment]
I believe you submit .tar files.  The jar would go in the .tar file.

**Comment by phillord** [comment]
With Marmalade, this would be possible, I think, unless Nic has
specially blocked it. With ELPA this might be possible, but ELPA
requires copyright assignment, which is just not going to happen short
term. With MELPA, no, it will not work. MELPA takes a recipe which is a
location to the source code VC (i.e. this repo!), then it generates the
actually tar ball for you. They will not support compilation of Java
files or any bespoke build.

There are lots of potential solutions to this, but my feeling is that we
will only recapitulate the route of CIDER, and that Bozhidar has already
hit on the correct solution. JDEE (in Marmalade/MELPA) contains lisp and
no Java, which has to be downloaded separately. In CIDER, this means it
comes as a maven dependency downloaded by the build tool.

JDEE currently has the nightmare of Emacs Lisp build with ant. Let's
build emacs-lisp with cask, Java with maven. Any otherway lies, well,
lies this:

    <exec dir="${build.lisp.escaped.dir}"
	  executable="${build.bin.emacs}" failonerror="true">
      <arg value="--no-site-file"/>
      <arg value="--batch"/>
      <arg value="--load"/>
      <arg value="${build.lisp.dst.escaped.file}"/>
    </exec>

Phil

**Comment by phillord** [comment]
Paul Landes <notifications@github.com> writes:

> I believe you submit .tar files.  The jar would go in the .tar file.
>
> On Aug 12, 2015, at 3:13 PM, Przemysław Wojnowski <notifications@github.com>
> wrote:
>
>> But what to do with Java code? Is it possible to upload a JAR to (m)ELPA?


We probably also need to make a rough decision about github vs mailing
list conversations!

Phil

**Comment by plandes** [comment]
This works for me.

**Comment by plandes** [comment]
I like how GH allows email response AND the web interface.  I'd be OK with dropping the lists--if possible (don't recall if I have admin rights).

However, there are many that still use the lists and I"m sure there are many who are unaware of the code base moving to GH at this point.  I suppose that's a moot point as SF mentions the GH project now.

**Comment by pwojnowski** [comment]
W dniu 2015-08-13 00:30, Paul Landes napisał(a):
> I like how GH allows email response AND the web interface. I'd be OK
> with dropping the lists--if possible (don't recall if I have admin
> rights).
I didn't know that one can respond by email to GH messages, which is 
cool. :-)

The problem I see is that these messages go only to people that are in 
the
project (I guess), and mailing list messages go to anyone subscribed 
there.
So both potentially can overlap only in a small part.

**Comment by plandes** [comment]
Good point.  Is there some way to forward the GH email to the list?

**Comment by phillord** [comment]
Register the mailing list as a github user[😊]


The problem is that replies to the mailing list will not go to github.


I think we just need to decide. I would argue that broad architectural decisions should be on the mailing list. Specific bug reports and discussion about them might as well be github.

________________________________

**Comment by dakrone** [comment]
> I would argue that broad architectural decisions should be on the mailing list.

Out of curiosity, (I don't mean to hijack the conversation), is the mailing list going to stay at sourceforge? It seems strange that the code moved elsewhere and the mailing list stays there.

**Comment by daveloyall** [comment]
I think that we should pick one and use it, even for long, detailed architecture discussions.  I think that GH Issues *are* a mailing list--with some good features.  I think we can have long discussions here.

I think the existing SF lists should be converted to "announce only" lists.  And each announcement should contain a link to the GH Issues list.  Perhaps in a year the lists could be closed for good.

(I think that dependency on GH is as bad as dependency on SF, but I have not heard of a good alternative.  My ears are open.)

**Comment by dakrone** [comment]
> My ears are open.

I've used http://librelist.com/ before with other OSS projects and it is nice.

**Comment by daveloyall** [comment]
@dakrone Dead links on the homepage and 2009 on the status page.  Anyway, I'll create a new term: 'corporate bus factor'.  Compare this to [bus factor](https://en.wikipedia.org/wiki/Bus_factor).

**Comment by plandes** [comment]
No matter how you slice bug and larger arch discussion cross.  Bug reports are the appropriate place for discussion that stems from commits or issues.  Let's use the mailing list for everything else (i.e. setup questions, arch discussion, coordination etc).

**Comment by dakrone** [comment]
Perhaps then the sourceforge page should be updated to indicate that even though the project is moved and deprecated, the mailing list is still "relevant"?

![screenshot from 2015-08-13 10-42-02](https://cloud.githubusercontent.com/assets/19060/9255660/076f8092-41a8-11e5-9d5e-dc01db0c09d9.png)

**Comment by plandes** [comment]
Done.

**Comment by dakrone** [comment]
Thanks!

**Comment by phillord** [comment]
Lee Hinman <notifications@github.com> writes:

>> I would argue that broad architectural decisions should be on the mailing list.
>
> Out of curiosity, (I don't mean to hijack the conversation), is the mailing
> list going to stay at sourceforge? It seems strange that the code moved
> elsewhere and the mailing list stays there.

I think the original idea was "one thing at a time". This was the day
before the source forge mailing lists broke.

Fixing the website, mailing lists and so forth would be good things to
do. Perhaps, we should add an issue about that also.

Phil

**Comment by daveloyall** [comment]
I said:

> I think that we should pick one and use it

No, I have changed my mind.  The bug tracker and mailing list shouldn't be the same thing.  Of course, most or all of you already know that. :)

Sorry for the noise!

**Comment by pwojnowski** [comment]
Sorry, but have to hijack the issues to come back to the original issue. :-)

I've create a branch with Cask build: https://github.com/jdee-emacs/jdee/tree/cask
Emacs lisp files are in the top directory and all tests pass.
With that setup we would be able to make jdee-emacs as an installable package and the Java part would need to be moved to separate project (jdee-server?) and (at least for now) installed separately.

One thing that bothers me is why I have to add current directory to test load path:
```cask exec ert-runner -L .``` - without that it cannot find JDEE files. :-|

**Comment by phillord** [comment]
Yep, that's a PITA. I normally use a .ert-runner file which loads everything.

https://github.com/phillord/lentic/blob/master/.ert-runner

For instance. The 

    cask exec ert-runner

should just work.

**Comment by pwojnowski** [comment]
cask branch has:
 - cask build
 - Makefile to ease common operations
 - travis setup copied from CIDER

If nobody mind I can merge it to master.

What needs to be done:
 - add to melpa
 - add to travis

**Comment by dakrone** [comment]
@pwojnowski I played around with the branch, looks cool.

Maybe in the readme instead of the cask instructions we want to use the `make` operations? It's also a little strange to use two build tools at once (cask and make) - wonder if in the future a test alias/command could be added to the cask file so someone could do `cask test` instead of `cask exec ert-runner -L .`

**Comment by pwojnowski** [comment]
You're right. Readme have to be updated with correct instructions.

It's strange to have both tools, but make allows to easily manage files and directories (rm -rf), which I haven't seen in cask. Maybe all this can be done with Cask, but I don't know (yet) how. Anyway, after the merge we can try to improve that.

**Comment by phillord** [comment]
Przemysław Wojnowski <notifications@github.com> writes:

> You're right. Readme have to be updated with correct instructions.
>
> It's strange to have both tools, but make allows to easily manage files and
> directories (rm -rf), which I haven't seen in cask. Maybe all this can be done
> with Cask, but I don't know (yet) how. Anyway, after the merge we can try to
> improve that.

I use make all the time to drive cask. It's fine, so long as there is a
clean and sane separation of functionality. Mostly I use it to avoid
having to remember the cask command line.

Phil

**Comment by dakrone** [comment]
> Mostly I use it to avoid having to remember the cask command line.

Hah yeah, Cask's command line is... non-obvious

**Comment by pwojnowski** [comment]
Merged.
I've got two problems now:
1. Cannot transfer pwojnowski/jdee-server to jdee-emacs, because I don't have admin rights in the organization. So @plandes needs to copy it or give admin rights.
2. Cannot setup travis build for the same reason (I've sent access request).

**Comment by plandes** [comment]
It's now copied but I don't know what to copy over fro the travis.  Can you forward me a URL.

**Comment by pwojnowski** [comment]
https://travis-ci.org/jdee-emacs/jdee

**Comment by plandes** [comment]
Copy that to github and then I'll fork it over to JDEE.

**Comment by plandes** [comment]
Wait I take that back.  I get this:

The repository at jdee-emacs/jdee was not found.

**Comment by pwojnowski** [comment]
You have to login to Travis with your GH account and go to "My Repositories". On the left there should be "Organizations", where you can add one. Then it will scan repos in the organization and then they will be available.

**Comment by pwojnowski** [comment]
I've renamed "jde" to "jdee" to make package conform to packaging rules.
I've tested the package and created a pull request to melpa (https://github.com/milkypostman/melpa/pull/3041).

**Comment by pwojnowski** [comment]
JDEE is on melpa.

**Comment by pwojnowski** [comment]
Greetings, 


How are you doing? I've  been thinking of you recently and I guess  I found  something  useful for  you, read more here <http://real.swanvisions.info/e4qmlqt>

Sent from my iPhone, Przemyslaw Wojnowski


576
