### ISSUE TITLE
jdee-compile leads to "Process bsh not running"errors

### ISSUE THREAD

**Issue by liar666** [jdee-emacs/jdee#32]
When I run jdee-compile on a (very simple) class, I see:

CompileServer output:

/usr/home/gmuller/test.java

I one buffer(?), then:
 "Process bsh not running"
in the "Messages"

**Comment by liar666** [comment]
Adding the bsh.jar to my jdee-global-classpath solves the problem

**Comment by ksinkar** [comment]
This problem can also be solved by downloading the jar file from http://beanshell.org/download.html and copying it to the `jdee-server-dir`.
