### ISSUE TITLE
Need a documentation for updaters

### ISSUE THREAD

**Issue by liar666** [jdee-emacs/jdee#33]
Since I updated from JDEE-2.4.1 to current git version (jdee-20151217.1405), almost nothing from my configuration file was working.

I tweaked a lot of things, looked all over the web, but nothing worked: my configuration simply seemed ignored.

I finally discovered that all the methods/variables were renamed from "jde-xxx" to "jdee-xxx".

Lots of time lost for such a simple thing :{ Would have been great to have a CHANGES file or a guide for people that simply upgrade their jdee version :)

**Comment by pwojnowski** [comment]
Thanks for reporting this. I've added CHANGES.md. Could you take a look at it and let me know if its fine? Would you add anything there?

Thank you!
