### ISSUE TITLE
typo in jdee-imenu.el?

### ISSUE THREAD

**Issue by ax006ho** [jdee-emacs/jdee#34]
I believe that there is a typo in file jdee-imenu.el in line 154 and line 156:

the functions `'semantic-sort-tokens-by-name-increasing-ci` and  `'semantic-sort-tokens-by-name-decreasing-ci` don't exist in cedet, but `'semantic-sort-tags-by-name-increasing-ci` and  `'semantic-sort-tags-by-name-decreasing-ci` do.

I assume `tokens` must be replaced by `tags`.

**Comment by pwojnowski** [comment]
That was it. Thank you! :+1:
