### ISSUE TITLE
JDE menu entry

### ISSUE THREAD

**Issue by ax006ho** [jdee-emacs/jdee#35]
I can create, compile and execute Java example files by short key cuts but I  don't get a JDE-entry in the menu bar. What went wrong or what can I do to make the JDE-entry appear?

**Comment by pwojnowski** [comment]
Seems to be fixed now.

**Comment by oldButNotWise** [comment]
I'm not sure it's fixed. The :set field in the def of jdee-menu-definition in jdee.el installs the menu only if (featurep 'infodock). Looking back over the history of the file, that appears to be a test intended only for xemacs. Removing the test does fix the problem.

**Comment by pwojnowski** [comment]
You were right about that. Good catch!

**Comment by ax006ho** [comment]
I can confirm the error is fixed now

**Comment by MichaelKazarian** [comment]
It not work for me. JDB menu isn't active and after run `jdee-debug-run` I got `Wrong type argument: (or eieio-object-p class-p), unbound`

**Comment by pwojnowski** [comment]
@MichaelKazarian JDEbug have been removed, but Jdb menu is there.
