### ISSUE TITLE
Broken autocomplete 

### ISSUE THREAD

**Issue by MichaelKazarian** [jdee-emacs/jdee#39]
When I try `jdee-complete-menu` after start `BeanShell` I have next error:
`Wrong numbers of arguments: (thing) "^H skip several symbols \207" [thing bounds thing-at-point bounds-of-thing-at-point] 3 (/usr/share/emacs/24.3/lisp/thingatpt.elc) 2`
Below my config:
```lisp
;;; JDEE start
(require 'jdee)
(setq jdee-server-dir "/home/kazarian/elisp/mode/jdee-server/target")
(jdee-set-variables
 '(jdee-jdk '("1.7"))
 '(jdee-jdk-registry '(("1.7" . "/usr/lib/jvm/java-7-oracle")))
 '(jdee-ant-enable-find t)
 '(jdee-compiler (quote ("javac server" "")))
 '(jdee-global-classpath (list
              "/usr/lib/jvm/java-7-oracle/jre/lib/rt.jar"
              "/opt/android-sdk-linux/platforms/android-16/android.jar"
              ))
;;; JDEE end
```

**Comment by pwojnowski** [comment]
I tried to reproduce the error with Emacs-master and Emacs 24.5 (the one in current Ubuntu), but everything works fine. Can you send a backtrace (e.g. toggle-debug-on-error)?

**Comment by MichaelKazarian** [comment]
All worked fine with jdee-20150824.214. My current environment: emacs 24.3 from ubuntu 14.04, cedet:
```
CEDET Version:	2.0
  			Requested	File		Loaded
  Package		Version		Version		Version
  ----------------------------------------------------------
  cedet:		2.0		ok		ok
  eieio:		1.4		ok		ok
  semantic:		2.2		ok		ok
  srecode:		1.2		ok		ok
  ede:			1.2		2.0		2.0
  cogre:		1.2		ok		Not Loaded
  cedet-contrib:	1.2		nil		Not Loaded
```

Error after upgrade to 20160116.1338. Backtrace below:
```
Debugger entered--Lisp error: (wrong-number-of-arguments #[(thing) "\302N\203\302N \207\303!\211\205	@	A{)\207" [thing bounds thing-at-point bounds-of-thing-at-point] 3 ("/usr/share/emacs/24.3/lisp/thingatpt.elc" . 2294)] 2)
  thing-at-point(symbol t)
  jdee-parse-qualified-name-at-point()
  jdee-parse-declared-type-of("l")
  jdee-parse-eval-type-of("l")
  jdee-complete-find-completion-for-pair(("l" "add") nil nil)
  jdee-complete-pair(("l" "add") t)
  byte-code("\302\303\304\"	\"\207" [pair completion-type jdee-complete-pair jdee-complete-get-pair t] 4)
  byte-code("\300\301\302\217\210\303\304\305\306!\"!\207" [err (byte-code "\302\303\304\"\"\207" [pair completion-type jdee-complete-pair jdee-complete-get-pair t] 4) nil error message "%s" error-message-string] 5)
  jdee-complete-generic(t)
  jdee-complete-menu()
  call-interactively(jdee-complete-menu)
  jdee-complete()
  call-interactively(jdee-complete nil nil)
```

**Comment by pwojnowski** [comment]
Let me know if that have fixed the problem. But I IMHO it should. Thanks for backtrace!

**Comment by MichaelKazarian** [comment]
now complete work fine

**Comment by oldButNotWise** [comment]
I'm the luser who broke the code; sorry about that. More recent versions of the function take an optional second argument to strip off text properties. I had not realized that earlier versions didn't have that capability.

My apologies.

**Comment by pwojnowski** [comment]
Relax, it's not your fault. IMHO Emacs' libs (API) could be better documented and use "Since x.y" (like in Java API) to depict when a function/var/argument have been introduced. This way we could easily learn which functions are safe to use across Emacsen. I reported that at emacs-devel, but they ignored me. Maybe I'll try again. :-)
