### ISSUE TITLE
Broken `jdee-wiz-override-method`

### ISSUE THREAD

**Issue by MichaelKazarian** [jdee-emacs/jdee#40]
After call `jdee-wiz-override-method` I get `*Completions*` buffer. But after choice of candidate for override I have next error:  `Error evaluating Java expresson. See *Messages* buffer.` But after switch to`*Messages*` I don't see any error message. Also enabling backtrace has no effect.
`jde-wiz-override-method` work fine under original `jde`.
P.S. Autocompletion works correctly now. Thanks.

**Comment by pwojnowski** [comment]
I've fix that. The problem was on the jdee-server side. Please rebuild it and it will work.

Thanks for reporting the issue! :+1:

**Comment by MichaelKazarian** [comment]
@pwojnowski It work  :+1:
