### ISSUE TITLE
Broken jde debug

### ISSUE THREAD

**Issue by MichaelKazarian** [jdee-emacs/jdee#41]
I can't run `jdee` debugger after set breakpoints. `C-c C-v C-d` has no effect. After call `jdee-debug-run` I have next error `Symbol's function defenition is void: unbound`
It work correctly in original `jde`

**Comment by pwojnowski** [comment]
I tried to reproduce the problem in Emacs-master, but everything works fine.

I'll try also with Emacs 24.5.

**Comment by MichaelKazarian** [comment]
@pwojnowski, my mistake [debuging with jde] (http://jdee.sourceforge.net/jdedoc/html/jdb-ug/jdb-ug-frame.html) fork fine. Broken [JDEbug] (http://jdee.sourceforge.net/jdedoc/html/jdebug-ug/jdebug-ug.html). Below my config for it:
```lisp
(jdee-project-file-version "1.0")
(jdee-set-variables
 '(jdee-compile-option-command-line-args (quote ("-g")))
 '(jdee-debugger (quote ("JDEbug")))
 '(jdee-sourcepath '("/home/kazarian/tmp/1/my-app/src/main/java" "/home/kazarian/tmp/1/my-app/src/test/java" ))
 '(jdee-global-classpath '("/home/kazarian/tmp/1/my-app/target/classes" "/home/kazarian/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar" "/home/kazarian/tmp/1/my-app/target/test-classes" )))
```
It must works [such manner](http://qiita.com/lambda-knight/items/3a6547e7aadb21fe4508#%E3%83%96%E3%83%AC%E3%83%BC%E3%82%AF%E3%83%9D%E3%82%A4%E3%83%B3%E3%83%88%E3%81%AE%E8%A8%AD%E5%AE%9A).
original `jde.jar` contains `debugger` directory, but `jdee-bundle-1.1-SNAPSHOT.jar-jar-with-dependencies.jar` don't contains it.

**Comment by pwojnowski** [comment]
See this message (from 2010): http://news.gmane.org/gmane.emacs.jdee.user/cutoff=469

It says that JDEbug was supposed to be removed and jdibug should be used as an alternative. Anyway, the class jde.debugger.Main is gone at least since 2010.

In which version did you see jde.debugger.Main? I cannot find it in sources from SourceForge. :-|

**Comment by oldButNotWise** [comment]
FWIW, I find that JDIBug works well, better than JDEbug. There's no integration with JDEE, but that's a minor issue.

**Comment by pwojnowski** [comment]
I've removed JDEbug from options. Sometime we'll integrate JDIbug with JDEE.
