### ISSUE TITLE
Multiple source paths?

### ISSUE THREAD

**Issue by liar666** [jdee-emacs/jdee#44]
Hi,

I'm currently working within a big project that is split in several parts, which are each managed in a independant svn "repos" (I don't like the "repos" term... In fact they are independant dirs in the same svn server). On my local machine, it looks like that:
- project-common/
- project-XXX/
- project-YYY/
- ...
Inside each project-xxx/ dir, you can find various files & dirs, notably ./src/ where the package tree structure can be found.

Of course, in most of the files in the project-xxx/src/ source code, we use methods from the project-commons/src/ classes.

Since, I didn't find any way to specify multiple jdee-sourcepath, every time I try to call jdee-open-class-at-point oni a class from project-common/ within the source code of a class in any project-xxx/ I get an error.

Is it possible to define multiple jdee-sourcepaths? How? If not is it a possible feature to add to jdee?

**Comment by oldButNotWise** [comment]
If these projects all share a common root directory, you can put a prj.el file at the root and one in each sub-project directory. When visiting a Java file all the prj.el files "above" it will be loaded, from the "top" down.

The variable jdee-sourcepath is a list of directories; you could then define it in the root prj file.

Or am I missing the point of the question entirely?

**Comment by liar666** [comment]
OK my bad, I tried that (bith having a prj.el "higher" in the tree and putting several paths in the jdee-sourcepath), but I just forgot a prj.el inside the project-xxx in which I tested, and it got in the way of the more general one :)
