### ISSUE TITLE
jdee-help-symbol url-type accessing a non-url

### ISSUE THREAD

**Issue by liar666** [jdee-emacs/jdee#53]
When I try to run "jdee-help-symbol" on a line of my code, I get error:
url-type accessing a non-url

I've tried running with "emacs -q" and setting minimal stuff (load jdee + server-dir) and I get the same error...

Did I go something wrong?

---

As a side question, when I try to run jdee-help-browse-jdk-doc on any line of my java code, I get:
eieio-generic-call-primary-only: Method jdee-url-name called on nil

I've tried running with "emacs -q" and setting minimal stuff (load jdee + server-dir) and I get no error!!! What did I configure incorrectly?
My prj.el file is quite big, but I think this part should be the most relevant with regards to the error I get:
 '(jdee-jdk (quote ("1.7.0")))
 '(jdee-jdk-doc-url "/usr/share/doc/openjdk-7-doc/api/index.html")
 '(jdee-jdk-registry (quote (("1.7.0" . "/usr/lib/jvm/java-7-openjdk-amd64/"))))
 '(jdee-make-working-directory "~/Work/Code/dist")
 '(jdee-run-working-directory "~/Work/Code/dist")
 '(jdee-server-dir "~/.emacs.d/elpa/jdee-20151217.1405/jars/")
 '(jdee-sourcepath ...)

**Comment by oldButNotWise** [comment]
Could you try `(setq jdee-jdk-doc-url "file:///usr/share/doc/openjdk-7-doc/api/index.html")`?

**Comment by liar666** [comment]
In t he case of jdee-help-symbol, I get some progress, the error is now:
Error: cannot find documentation for class java.util.Set 
In the case of jdee-help-browse-jdk-doc, I still get:
eieio-generic-call-primary-only: Method jdee-url-name called on nil

**Comment by fseibel** [comment]
The problem is that in the latest version of eieio instantiating a class with a string arg no longer generates an automatic name member.  I have fixed this problem in the class jdee-url by adding an explict name member and modifying the few places the name was referenced and where instantiated. 
[jdee-help.zip](https://github.com/jdee-emacs/jdee/files/814123/jdee-help.zip)

**Comment by pwojnowski** [comment]
Good catch! Do you want to create a Pull Request?

**Comment by fseibel** [comment]
I really don’t know anything about Github other than a repository for a few of the packages I use.  You or anyone else is welcome to use the file I uploaded with my comment to fix the bug in the distribution.

Fred

**Comment by pwojnowski** [comment]
Thank you! :1st_place_medal:
