### ISSUE TITLE
Completing a String method results in an error 

### ISSUE THREAD

**Issue by liar666** [jdee-emacs/jdee#55]
In the following lines

```
String a = "JSON";
if ("HTML".equalsIgno...(a)) { xxx }
```
If I try to "jdee-complete" where the "..." are, I get the following error :

Beanshell expression evaluation error.
  Expression: {
  boolean _prevShowValue = this.interpreter.getShowResults();
  Object _retVal = null;
  this.interpreter.setShowResults(false);
  _jdeCustEvalFn() { jde.util.JdeUtilities.getQualifiedName(""HTML""); };
  try { _retVal = eval("_jdeCustEvalFn();"); }
  finally {
    this.interpreter.setShowResults(_prevShowValue);
  }
  if (_retVal != null) print(_retVal);
}
  Error: // Error: Parser Error: In file: <unknown> Encountered "( \"\" HTML" at line 39, column 60.
 [2 times]
Beanshell expression evaluation error.
  Expression: {
  boolean _prevShowValue = this.interpreter.getShowResults();
  Object _retVal = null;
  this.interpreter.setShowResults(false);
  _jdeCustEvalFn() { jde.util.JdeUtilities.classExists("HTML"); };
  try { _retVal = eval("_jdeCustEvalFn();"); }
  finally {
    this.interpreter.setShowResults(_prevShowValue);
  }
  if (_retVal != null) print(_retVal);
}
  Error: // Error: Error parsing input: bsh.TokenMgrError: Lexical error at line 1, column 7.  Encountered: "\n" (10), after : "\"); };"

**Comment by pwojnowski** [comment]
I've tried that in old JDE-2.4.2 and it also didn't work.
