### ISSUE TITLE
jdee-master: useful key shortcuts disappeared. 

### ISSUE THREAD

**Issue by Reissner** [jdee-emacs/jdee#57]
How can i get back my cool key shortcuts cvc and cvr above all??? 
Good thing that now java 1.7 and 1.8 are supported.

**Comment by pwojnowski** [comment]
Which JDEE and Emacs versions do you use? In the MELPA versions all the shortcuts are there.

Is JDEE loaded when you visit a Java file?

**Comment by pwojnowski** [comment]
The shortcuts work correctly. If you still have this issue, please reopen it. Thanks!
