### ISSUE TITLE
No more "JDE" menu??

### ISSUE THREAD

**Issue by liar666** [jdee-emacs/jdee#59]
Hi,

I recently realized that the JDE menu has disappeared from my menu bar (thus no more compile/run/javadoc/etc entries accessible).
Now I only have: File Edit Buffers Tools Classes Java Development Jdb Help
Inside Java there is almost nothing: [un]comment / Indent / Fill / BckFwdStatment / Style / Toogle
I can't find a way to get the actual & complete menu back!!!

I've tried to go to the customize-group jde-project (as referenced in the jde-imenu.el file) but many entries are empty and not settable...

**Comment by pwojnowski** [comment]
Which JDEE and Emacs versions do you use?

About half a year ago there was such problem - #35 - but it has been fixed and I do have JDEE menu.

**Comment by liar666** [comment]
That was it, thanks :)

I dont know why I had the overly outdated jdee-20151217.1405 from ELPA...
