### ISSUE TITLE
add support for jdk 1.7 and 1.8 e.g. in jdee-run.el 

### ISSUE THREAD

**Issue by Reissner** [jdee-emacs/jdee#62]
Maybe to add support of 1.8 and 1.7 just add at proper place 

(defclass jdee-run-vm-1-7 (jdee-run-vm-1-6) ()
  "Represents the JDK 1.7.x vm")

(defmethod initialize-instance ((this jdee-run-vm-1-7) &rest fields)
  "Constructor for the class representing the JDK 1.7 vm."

  ;; Call parent initializer.
   (call-next-method)

   (oset this :version "1.7"))

 (defclass jdee-run-vm-1-8 (jdee-run-vm-1-7) ()
   "Represents the JDK 1.8.x vm")

 (defmethod initialize-instance ((this jdee-run-vm-1-8) &rest fields)
   "Constructor for the class representing the JDK 1.8 vm."

   ;; Call parent initializer.
   (call-next-method)

   (oset this :version "1.8"))

and also 

(defvar jdee-run-virtual-machines
  (list
   (jdee-run-vm-1-1 "JDK 1.1 vm")
   (jdee-run-vm-1-2 "JDK 1.2 vm")
   (jdee-run-vm-1-3 "JDK 1.3 vm")
   (jdee-run-vm-1-4 "JDK 1.4 vm")
   (jdee-run-vm-1-5 "JDK 1.5 vm")
   (jdee-run-vm-1-6 "JDK 1.6 vm")
   (jdee-run-vm-1-7 "JDK 1.7 vm")
   (jdee-run-vm-1-8 "JDK 1.8 vm"))
  "*List of supported virtual machines.")

Maybe this is not all to be done. 
I am not a lisp programmer...

**Comment by m0smith** [comment]
Added with pr-76

**Comment by pwojnowski** [comment]
Fixed is part of #76 . Thanks!
