### ISSUE TITLE
jdee-show-help: Cannot find JDEE help file.

### ISSUE THREAD

**Issue by liar666** [jdee-emacs/jdee#65]
Clicking in the JDEE>Help>Jdee Users Guide menu entry, I get:
jdee-show-help: Cannot find JDEE help file.

**Comment by oldButNotWise** [comment]
The problem here is that the code has changed the path names from "jde-" to "jdee-", but the help files have not been renamed.

**Comment by pwojnowski** [comment]
HTML docs are using some applet that doesn't work anymore (at least I wasn't able to run it). So to fix that someone would need to do some work with it - remove or repair. But do we need HTML docs for JDEE? Isn't info enough?

The easiest fix would be just to call: ```(info "(jdee)User's Guide")``` from the function to just open the docs in Info format inside Emacs.

**Comment by liar666** [comment]
Hi,

> (info "(jdee)User's Guide")
Yes, I think that would do it.



-- 
Guillaume MULLER, PhD
Presans c/o REMIX COWORKING - L'APPART
57 rue de Turbigo
75003 Paris
France
http://www.presans.com
http://feeds.feedburner.com/OYI/fr
