### ISSUE TITLE
About jdee-import-find-and-import and name conflicts...

### ISSUE THREAD

**Issue by liar666** [jdee-emacs/jdee#69]
Hi,

I just positioned my cursor on the word IOUtils in my code and called jdee-import-find-and-import. As a results, in the mini-buffer, appeared a message saying "Excluding sun.misc.IOUtils".

What I want to use in my code is org.apache.commons.io.IOUtils. 

In my prj.el I have:
 '(jdee-global-classpath (quote (... "~/Code/my-libs/jars/*" ...)))

Where:
$ ls ~/Code/my-libs/jars/commons-*
my-libs/jars/commons-beanutils-1.8.3.jar
my-libs/jars/commons-beanutils-bean-collections-1.8.3.jar
my-libs/jars/commons-beanutils-core-1.8.3.jar
my-libs/jars/commons-cli-1.0.jar
my-libs/jars/commons-codec-1.9.jar
my-libs/jars/commons-collections-3.2.jar
my-libs/jars/commons-io-2.4.jar
my-libs/jars/commons-lang-2.3.jar
my-libs/jars/commons-logging-1.0.4.jar
my-libs/jars/commons-net-1.4.1.jar
my-libs/jars/commons-pool-1.3.jar
my-libs/jars/commons-validator-1.3.1.jar

As you can see, commons-io is in my CLASSPATH, so I don't understand why jdee-import-find-and-import does not enter interactive mode and propose to select one of the options?

Might be related to #66

**Comment by pwojnowski** [comment]
Hi! Could you try with the newest JDEE (20161205)? I corrected a few things and it works correctly now.

**Comment by liar666** [comment]
That's better, now it proposes the apache libs. Big Thanks!
