### ISSUE TITLE
"Cannot open load file" "no such file or directory" "jdee-test"

### ISSUE THREAD

**Issue by liar666** [jdee-emacs/jdee#79]
I've just upgraded to lastest jdee from ELPA. 

When opening a java file, I get:
```
Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" "jdee-test")
  require(jdee-test)
  eval-buffer(#<buffer  *load*-899972> nil "/home/xxx/.emacs.d/elpa/jdee-20161102.531/jdee.el" nil t)  ; Reading at buffer position 1882
  load-with-code-conversion("/home/xxx/.emacs.d/elpa/jdee-20161102.531/jdee.el" "/home/xxx/.emacs.d/elpa/jdee-20161102.531/jdee.el" nil t)
  require(jdee)
  eval-buffer(#<buffer  *load*> nil "/home/xxx/.emacs" nil t)  ; Reading at buffer position 14343
  load-with-code-conversion("/home/xxx/.emacs" "/home/xxx/.emacs" t t)
  load("~/.emacs" t t)
...
  command-line()
  normal-top-level()
```

**Comment by liar666** [comment]
Commenting out require(jdee-test) in jdee.el seems to work around the problem for now...

**Comment by pwojnowski** [comment]
Thanks for the bug report. I created MELPA PR to fix this. It's tracked in #81.

**Comment by liar666** [comment]
I just updated another machine and got the same error for require(dash).
I don't know Emacs's package system, so I don't know if it is possible to do so, you might need to add a dependancy of jdee to dash...

**Comment by m0smith** [comment]
Does dash just need to be added to the Cask file?

**Comment by pwojnowski** [comment]
AFAIK package requirements have to be added to the package file (jdee.el in our case) specified in Cask - see [Library Headers](http://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html#Library-Headers). Deps specified in Cask/development section are only for development (tests?) and will not be included in packaged library, only the libs from "Library Headers".
