### ISSUE TITLE
lack of jdee-test.el in melpa

### ISSUE THREAD

**Issue by MichaelKazarian** [jdee-emacs/jdee#81]
subj for jdee-20161102.531

**Comment by pwojnowski** [comment]
This is because default MELPA recipe format, which excludes, among others, *-test.el - [MELPA Recipe Format](https://github.com/melpa/melpa#recipe-format).

**Comment by pwojnowski** [comment]
Created PR in MELPA: https://github.com/melpa/melpa/pull/4391

**Comment by pwojnowski** [comment]
A build from the corrected recipe is available and contains jdee-test.
