### ISSUE TITLE
jdee-devel at sourceforge down since 17 July

### ISSUE THREAD

**Issue by stephe-ada-guru** [jdee-emacs/jdee#9]
Every email I've sent to jdee-devel@lists.sourceforge.net from 17 July on has bounced, and the archive shows no messages for that period as well.

Can that be fixed, or is it time for a new mailing list?

**Comment by pwojnowski** [comment]
SF was down for almost a week and it seems that mailing lists still are not fully operational.
Now at least the list is accessible through web page: http://sourceforge.net/p/jdee/mailman/jdee-devel/
Yesterday I've sent an email, but it bounced. :-|

**Comment by pwojnowski** [comment]
Seems that the list is back.
