### ISSUE TITLE
jdee-flycheck issue

### ISSUE THREAD

**Issue by MichaelKazarian** [jdee-emacs/jdee#92]
Jdee claims
Error while checking syntax automatically: (unbound-slot "#<class jdee-flycheck-compiler>" "#<jdee-flycheck-compiler flycheck>" :interactive-args oref)

and open several temp buffers like /tmp/JDEE_flycheck_11317H5h/CheckLearnActivity.java

Jdee version 20161130.1311
Flycheck version: 31snapshot (package: 20161117.144)

**Comment by pwojnowski** [comment]
Could you post a stacktrace or tell how to recreate it? Thanks!

**Comment by MichaelKazarian** [comment]
Debugger entered--Lisp error: (unbound-slot "#<class jdee-flycheck-compiler>" "#<jdee-flycheck-compiler flycheck>" :interactive-args oref)
  signal(unbound-slot ("#<class jdee-flycheck-compiler>" "#<jdee-flycheck-compiler flycheck>" :interactive-args oref))
  #[257 "\300 \210\301@A\"\207" [flycheck-report-failed-syntax-check signal] 4 "\n\n(fn ERR)"]((unbound-slot "#<class jdee-flycheck-compiler>" "#<jdee-flycheck-compiler flycheck>" :interactive-args oref))
  funcall(#[257 "\300 \210\301@A\"\207" [flycheck-report-failed-syntax-check signal] 4 "\n\n(fn ERR)"] (unbound-slot "#<class jdee-flycheck-compiler>" "#<jdee-flycheck-compiler flycheck>" :interactive-args oref))
  flycheck-buffer()
  #[0 "\300 \207" [flycheck-buffer] 1 "\n\n(fn)"]()
  funcall(#[0 "\300 \207" [flycheck-buffer] 1 "\n\n(fn)"])
  flycheck-buffer-automatically()
  flycheck-perform-deferred-syntax-check()
  set-window-buffer(nil #<buffer CheckLearnActivity.java>)
  switch-to-buffer(#<buffer CheckLearnActivity.java>)
  find-file("~/a/WordRunner/app/src/main/java/com/waverunner/wordrunner/CheckActivity.java" t)
  call-interactively(find-file nil nil)
  command-execute(find-file)

**Comment by pwojnowski** [comment]
I'm not sure this is JDEE problem. Can change the implementation of ```find-file``` to the following:
```emacs-lisp
(interactive
   (find-file-read-args "Find file: "
                        (confirm-nonexistent-file-or-buffer)))
  (let ((value (find-file-noselect filename nil nil wildcards)))
    (message "buffer is: %s" value) ; added to see what buffer is find
    (if (listp value)
	(mapcar 'switch-to-buffer (nreverse value))
      (switch-to-buffer value)))
```
In my case the message is "buffer is: AbstractClassFactory.java".

**Comment by MichaelKazarian** [comment]
where I can change implementation?

**Comment by m0smith** [comment]
At line 727 of try adding
`                     :initform nil`

so it looks like
`   (interactive-args :initarg :interactive-args
                     :initform nil
		     :type list
		     :documentation
		     "Arguments entered in the minibuffer.")`

You will need to evaluate jdee-compile and jdee-flycheck or it to take effect.

It this works, I'll submit the pull request.

**Comment by MichaelKazarian** [comment]
@m0smith Better. jdee normally run. But now jdee ignore sourcepath defined below;
```lisp
(jdee-set-variables
;....
  '(jdee-sourcepath '("./app/src/main/java"
                      "./app/src/test/java"
                      "./app/build/generated/source/r/debug"))
  '(jdee-built-class-path '("./app/build/intermediates/classes/debug"))
  '(jdee-compile-option-directory "./app/build/intermediates/classes/debug")
;....
)
```

**Comment by MichaelKazarian** [comment]
@m0smith [here my flymake cheker](https://gist.github.com/MichaelKazarian/334aeef228ca2a9cddc3058b34c77a38). It correct works with `jdee-sourcepath`.

**Comment by MichaelKazarian** [comment]
> If this works, I'll submit the pull request.

@m0smith Can you submit the pull request?

**Comment by m0smith** [comment]
Looks like it is there

**Comment by MichaelKazarian** [comment]
After update to 20161207.1325 I have obtained next message: `Compilation exited abnormally with code 2`. Sadly, I can't retrieve stacktrace.

**Comment by MichaelKazarian** [comment]
@m0smith After update to 20161207.1325 I have obtained next message: `Compilation exited abnormally with code 2`. Sadly, I can't retrieve stacktrace.

**Comment by m0smith** [comment]
There should be a buffet with the output of the compilation that might help

**Comment by MichaelKazarian** [comment]
@m0smith Bug in my mind. I forgot update some path in my project

**Comment by m0smith** [comment]
What did you forget to set?

**Comment by MichaelKazarian** [comment]
@m0smith Until this bug not fixed I worked with AndroidStudio. In this time platform has updated and I forgot `gradle installDebug` for update all paths before run `flycheck-mode`. So I catched `Compilation exited abnormally with code 2`

**Comment by pwojnowski** [comment]
I've looked at this and found the following:
1. Errors are collected correctly, which can be seen in Flycheck: ```C-c ! l```
2. I still don't know why the last line of compilation buffer (Compilation exited abnormally with code 1) ends up in *Messages* buffer and the minibuffer. I've added a call to display flycheck errors and now the errors appear in the minibuffer, which is more helpful and aligned with, for instance, flycheck-python-checker.

BTW I've switched whole file to lexical binding and didn't see any issues. @m0smith do you think that this may pose problems? If so, where?

@MichaelKazarian is it now working as expected?

**Comment by plandes** [comment]
You might be getting it in both the mini and message buffers because you have some async piped process running (i.e. compilation-finish-functions).  On completion async procs report progress to the mini buffer esp.  if exiting failure.

**Comment by MichaelKazarian** [comment]
@pwojnowski

> is it now working as expected?

Yes

**Comment by m0smith** [comment]
@pwojnowski The "Compilation exited abnormally with code 1" is coming from the compilation-mode.  It is hard coded that way in a large method.  I tried to find a way to hide the message but couldn't.

I generally do all my coding in lexical mode as it is easier to think that way.  For some reason I couldn't with that file but I do not remember why and may have worked through the issue without knowing it.  I was probably one of the functions with cback as a argument.  If they are working now in lexical mode that is all for the better.
