### ISSUE TITLE
can't find jdk

### ISSUE THREAD

**Issue by jenia** [jdee-emacs/jdee#96]
Hello.

When I run `M-x jdee-run` I get: "Cannot find JDK directory. See `jdee-jdk`.

I tried to point emacs to the JDK by doing `(add-to-list 'load-path "C:\Program Files\Java\jdk1.8.0_111")` in the .emacs file but it didn't help.

How do I fix this problem?

Thanks

**Comment by pwojnowski** [comment]
Could you evaluate this: ```(jdee-jdk-build-default-registry)``` and tell what it returns?

**Comment by pwojnowski** [comment]
Please reopen the issue if it's still a problem. Thanks.

**Comment by ChillarAnand** [comment]
I have set 

```
jdee-jdk-registry is a variable defined in `jdee-jdk-manager.el'.
Its value is (("1.9" . "/usr/lib/jvm/java-9-openjdk-amd64"))
```

Still its throwing error.
