### ISSUE TITLE
Disabling flycheck for Java syntax on opening a new *.java file

### ISSUE THREAD

**Issue by purukaushik** [jdee-emacs/jdee#97]
Not really an issue, more of a question.

I would like to disable flycheck mode globally for *.java files. I see no options for java when I hit `M-x` and try something `flycheck-java-`. Seems like flycheck doesn't [support](http://www.flycheck.org/en/latest/languages.html) java, but I have no idea how flycheck starts with Jdee for any `*.java` file and would like to disable it, since I can always `C-c C-v C-c` to compile my code.

My dev stack is:
Ubuntu - 15.10
GNU Emacs  - 24.5.1
JDEE - 20170102.757 (from `M-x list-packages`, installed from melpa via `M-x package-install`)
FlyCheck 20170101.1502

**Comment by pwojnowski** [comment]
There was no such option, but I've just added ```jdee-flycheck-enable-p```, which you can customize and have Flycheck disabled in JDEE. Just wait for the MELPA build.

I really appreciate that you've provided versions! :+1:

**Comment by purukaushik** [comment]
Thanks @pwojnowski

**Comment by purukaushik** [comment]
@pwojnowski 
So this is what I did today:
1. `M-x` list-packages and the in `**Packages**` buffer `U-x` to update all packages.
2. After updating from MELPA, in a normal buffer `M-x` then `jdee-customize-variable` -> search for `jdee-flycheck-enable-p` -> toggle it to `nil` from `non-nil`.
3. Closed current emacs session and opened a file `*.java` in a new session.
4. I see that flycheck is still enabled on startup.

Is there a way to disable flycheck across sessions? Like something I can set in `.emacs` or `.emacs.d/init.el`. Pardon me for being a tyro with the `init.el` settings and stuff, I am still learning my emacs.

Version of jdee-emacs : 20170109.113

**Comment by pwojnowski** [comment]
But what do you mean that Flycheck is enabled? Did JDEE start Bsh and you see highlighted compilation errors? If so, what is value of the ```jdee-flycheck-enable-p``` when you are in a java file?

BTW even when JDEE does not run Flycheck you can see "FlyC" in the mode line if you have global-flycheck-mode turned on. But it doesn't mean that the jdee-flycheck is actually running.

**Comment by purukaushik** [comment]
I guess I have `global-flycheck-mode` turned on. Will try disabling that. Thanks

**Comment by pwojnowski** [comment]
Sorry, I wasn't clear enough. You don't have to disable global-flycheck-mode.

Flycheck itself doesn't do any checks - it just runs checkers registered for the current mode. So, when no checkers are registered for the current mode, Flycheck will run nothing. In case of JDEE we've got ```jdee-flycheck-enable-p``` flag, which when nil, prevents registration of our jdee-flycheck-checker. It means that even though Flycheck is globally enabled, it won't run JDEE's checker, because it isn't registered. So there's no need to disable Flycheck globally.

Hope it makes sense. :-)

**Comment by purukaushik** [comment]
Hey, so this is what I am facing:
1. I open a file `*.java` in emacs.
2. I have `FlyC` enabled by default for any java file.
3. I would like to disable this, so I try this `M-x` customize-variable -> `jdee-flycheck-enable-p` set it to nil to disable flycheck on each java buffer.
4. I shutdown emacs and open a `*.java` file.
5. I still see `FlyC` mode turned on.
6. So now  I try  setting `(global-flycheck-mode -1)` in `~/.emacs.d/init.el`, still doesnt work


My `[init.el]`(https://gist.github.com/purukaushik/47e5956ee7a8a0b2791b71e75d5b1593) if it helps.

**Comment by peterbecich** [comment]
@purukaushik if it's helpful at all, my Emacs configuration for C, C++ and Objective-C caused problems for JDEE.  Commenting out all this stuff related to rtags and irony modes kept Flycheck and Rtags from loading with JDEE: https://github.com/peterbecich/dotfiles/blob/master/emacs/areas/c.el#L15-L62
